# gen-ftypes.awk -- derive lvx-ftypes.def from lvx-builtins.def.
#
# Every DEF_LVX_FTYPE exists because some builtin asks for that signature, so
# the list is a function of lvx-builtins.def alone and is generated from it at
# build time rather than maintained by hand (it had drifted by 181 entries).
# A builtin's optional arguments, when it has any, give it a second signature
# as well as the long one, since both are callable.
#
# Run as:  LC_ALL=C awk -f gen-ftypes.awk lvx-builtins.def > lvx-ftypes.def
# The output is sorted bytewise, so it does not depend on the builder's
# locale; LC_ALL=C makes awk's string comparison bytewise too.

function add(args, n,    i, s) {
    s = args[1]
    for (i = 2; i <= n; i++) s = s ", " args[i]
    seen[sprintf("DEF_LVX_FTYPE (%d, (%s))", n - 1, s)] = 1
}

{
    if (!match($0, /[^ ]*FTYPE[^,]*,[^,]*/)) next
    field = substr($0, RSTART, RLENGTH)
    nf = split(field, f, ",")

    sig = f[1]
    sub(/_FTYPE_?/, "_", sig)
    n = 0
    m = split(sig, parts, "_")
    for (i = 1; i <= m; i++) if (parts[i] != "") args[++n] = parts[i]
    add(args, n)

    # The optional arguments, when there are any, give a second signature.
    opt = (nf >= 2) ? f[2] : ""
    gsub(/[ \t]/, "", opt)
    m = split(opt, parts, "_")
    extra = 0
    for (i = 1; i <= m; i++) if (parts[i] != "") { args[++n] = parts[i]; extra++ }
    if (extra) add(args, n)
    delete args
}

END {
    print "/* Generated by gen-ftypes.awk -*- buffer-read-only: t -*- vi:set ro: */"
    print ""
    print "/* lvx-ftypes.def -- List of the compiler builtins types of the LVX backend."
    print ""
    print "   Copyright (C) 1991-2024 Free Software Foundation, Inc."
    print "   Contributed by Kalray SA."
    print ""
    print "   This file is part of GCC."
    print ""
    print "   GCC is free software; you can redistribute it and/or modify it"
    print "   under the terms of the GNU General Public License as published"
    print "   by the Free Software Foundation; either version 3, or (at your"
    print "   option) any later version."
    print ""
    print "   GCC is distributed in the hope that it will be useful, but WITHOUT"
    print "   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY"
    print "   or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public"
    print "   License for more details."
    print ""
    print "   Under Section 7 of GPL version 3, you are granted additional"
    print "   permissions described in the GCC Runtime Library Exception, version"
    print "   3.1, as published by the Free Software Foundation."
    print ""
    print "   You should have received a copy of the GNU General Public License and"
    print "   a copy of the GCC Runtime Library Exception along with this program;"
    print "   see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see"
    print "   <http://www.gnu.org/licenses/>.  */"
    print ""
    # Sorted bytewise: a plain insertion sort, since POSIX awk has none.
    n = 0
    for (k in seen) keys[++n] = k
    for (i = 2; i <= n; i++) {
        v = keys[i]
        for (j = i - 1; j >= 1 && keys[j] > v; j--) keys[j + 1] = keys[j]
        keys[j + 1] = v
    }
    for (i = 1; i <= n; i++) print keys[i]
}
