#!/usr/bin/env ruby

# genftype.rb -- Compiles all the builtin types in a list
#
#  Copyright (C) 1991-2024 Free Software Foundation, Inc.
#  Contributed by Kalray SA.
#
#  This file is part of GCC.
#
#  GCC is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published
#  by the Free Software Foundation; either version 3, or (at your
#  option) any later version.
#
#  GCC is distributed in the hope that it will be useful, but WITHOUT
#  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
#  or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
#  License for more details.
#
#  Under Section 7 of GPL version 3, you are granted additional
#  permissions described in the GCC Runtime Library Exception, version
#  3.1, as published by the Free Software Foundation.
#
#  You should have received a copy of the GNU General Public License and
#  a copy of the GCC Runtime Library Exception along with this program;
#  see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see
#  <http://www.gnu.org/licenses/>.  */

require 'optparse'

builtins_file = 'lvx-builtins.def'
output_file = STDOUT

OptionParser.new do |opts|
  opts.banner = "Usage: genftype.rb [file1 [file2 ...]] -o ofile\n" \
    "Reads stdin when no files are given"

  opts.on("-o", "--output FILE", "The output file. Defaults to stdout.") do |f|
    output_file = f
    end

  opts.on_tail("-h", "--help", "Show this message") do
    puts opts
    exit
  end
end.parse!

ARGV << builtins_file if ARGV.empty?

table = []
ARGF.readlines.each do |line|
  if line =~ /([^ ]*FTYPE[^,]*,[^,]*)/
    args, *varargs = $1.split(',').map { |t| t.gsub(/_FTYPE_?/, '_').split('_').map(&:strip) }
    varargs = varargs.flatten
    table << "DEF_LVX_FTYPE (#{args.size - 1}, (#{args.join(', ')}))"
    unless varargs.empty?
      full_args = args + varargs
      table << "DEF_LVX_FTYPE (#{full_args.size - 1}, (#{full_args.join(', ')}))"
    end
  end
end

out = STDOUT
out = File.open(output_file, 'w') unless output_file == STDOUT

out.puts <<-HEADER
/* Generated by genftype.rb -*- buffer-read-only: t -*- vi:set ro: */

/* lvx-ftypes.def -- List of the compiler builtins types of the LVX backend.

   Copyright (C) 1991-2024 Free Software Foundation, Inc.
   Contributed by Kalray SA.

   This file is part of GCC.

   GCC is free software; you can redistribute it and/or modify it
   under the terms of the GNU General Public License as published
   by the Free Software Foundation; either version 3, or (at your
   option) any later version.

   GCC is distributed in the hope that it will be useful, but WITHOUT
   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
   or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
   License for more details.

   Under Section 7 of GPL version 3, you are granted additional
   permissions described in the GCC Runtime Library Exception, version
   3.1, as published by the Free Software Foundation.

   You should have received a copy of the GNU General Public License and
   a copy of the GCC Runtime Library Exception along with this program;
   see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see
   <http://www.gnu.org/licenses/>.  */

HEADER

table.sort!.uniq!
table.each do |entry|
  out.puts entry
end

out.close unless output_file == STDOUT
