/*

   Copyright (C) 2009-2018 Kalray SA.

This file is part of GCC.

GCC is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3, or (at your option)
any later version.

GCC is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
License for more details.

You should have received a copy of the GNU General Public License
along with GCC; see the file COPYING3.  If not see
<http://www.gnu.org/licenses/>.  */

#ifndef LVX_OPTS_H
#define LVX_OPTS_H

enum lvx_arch_type
{
  LVX_ARCH_LVX_1,
  LVX_ARCH_LVX_2
};

/* lvx-2 is a strict extension of lvx-1: every lvx-1 instruction exists on
   lvx-2 (checked against opcodes/lvx-opc.c -- 0 mnemonics are lvx_v1-only,
   293 are lvx_v2-only).  So LVX is "any LVX", LVX_1 means "exactly lvx-1"
   and LVX_2 gates everything the SIMD surface needs.  */
#define LVX (1)
#define LVX_1 (lvx_arch_name == LVX_ARCH_LVX_1)
#define LVX_2 (lvx_arch_name == LVX_ARCH_LVX_2)

#define HAVE_LVX_FP_CONV_WITH_SHIFT (0)
#define HAVE_LVX_SILENT_FP_OPS (0)
#define HAVE_LVX_ADDRESSING_XS (0)
#define HAVE_LVX_MODIFIER_SX (1)
#define HAVE_LVX_PREDICATION (1)

#define HAVE_LVX_ABD_ONLY_I32_IMMEDIATE (LVX_1)
#define HAVE_LVX_MULD_ONLY_I32_IMMEDIATE (1)
#define HAVE_LVX_COMPD_ONLY_I32_IMMEDIATE (LVX_1)
#define HAVE_LVX_COMP_SIDI_ALL_NALL (0)
#define HAVE_LVX_COMPD_MAX_IMMEDIATE_I32 (LVX_1)
#define HAVE_LVX_CMOVED_MAX_IMMEDIATE_I32 (LVX_1)

#define HAVE_LVX_ATOMIC_LOAD_SI  (1)
#define HAVE_LVX_ATOMIC_LOAD_DI  (1)
#define HAVE_LVX_ATOMIC_STORE_SI (1)
#define HAVE_LVX_ATOMIC_STORE_DI (1)
#define HAVE_LVX_ATOMIC_CV1_LIKE_LOAD_CLEAR_SI (0)
#define HAVE_LVX_ATOMIC_CV1_LIKE_LOAD_CLEAR_DI (0)
#define HAVE_LVX_ATOMIC_CV2_LIKE_LOAD_CLEAR_SI (1)
#define HAVE_LVX_ATOMIC_CV2_LIKE_LOAD_CLEAR_DI (1)
#define HAVE_LVX_ATOMIC_CV1_LIKE_LOAD_PLUS_SI (0)
#define HAVE_LVX_ATOMIC_CV1_LIKE_LOAD_PLUS_DI (0)
#define HAVE_LVX_ATOMIC_CV2_LIKE_LOAD_PLUS_SI (1)
#define HAVE_LVX_ATOMIC_CV2_LIKE_LOAD_PLUS_DI (1)
#define HAVE_LVX_ATOMIC_VALUED_CSWAP_SI (1)
#define HAVE_LVX_ATOMIC_VALUED_CSWAP_DI (1)
#define HAVE_LVX_ATOMIC_VALUED_CSWAP_TI (1)

#define HAVE_LVX_ABD_SI (1)
#define HAVE_LVX_ABD_DI (1)
#define HAVE_LVX_ABD_V2SI (1)
#define HAVE_LVX_ABD_V4HI (1)
#define HAVE_LVX_ABD_V8QI (1)
#define HAVE_LVX_ABD_V2DI (1)
#define HAVE_LVX_ABD_V4SI (1)
#define HAVE_LVX_ABD_V8HI (1)
#define HAVE_LVX_ABD_V16QI (1)
#define HAVE_LVX_ABD_V4DI (1)
#define HAVE_LVX_ABD_V8SI (1)
#define HAVE_LVX_ABD_V16HI (1)
#define HAVE_LVX_ABD_V32QI (1)

#define HAVE_LVX_ABS_DI (1)
#define HAVE_LVX_ABS_V2SI (1)
#define HAVE_LVX_ABS_V4HI (1)
#define HAVE_LVX_ABS_V8QI (1)
#define HAVE_LVX_ABS_V2DI (1)
#define HAVE_LVX_ABS_V4SI (1)
#define HAVE_LVX_ABS_V8HI (1)
#define HAVE_LVX_ABS_V16QI (1)
#define HAVE_LVX_ABS_V4DI (1)
#define HAVE_LVX_ABS_V8SI (1)
#define HAVE_LVX_ABS_V16HI (1)
#define HAVE_LVX_ABS_V32QI (1)

#define HAVE_LVX_ASHIFT_DI (1)
#define HAVE_LVX_ASHIFT_V2SI (1)
#define HAVE_LVX_ASHIFT_V4HI (1)
#define HAVE_LVX_ASHIFT_V8QI (1)
#define HAVE_LVX_ASHIFT_V2DI (1)
#define HAVE_LVX_ASHIFT_V4SI (1)
#define HAVE_LVX_ASHIFT_V8HI (1)
#define HAVE_LVX_ASHIFT_V16QI (1)
#define HAVE_LVX_ASHIFT_V4DI (1)
#define HAVE_LVX_ASHIFT_V8SI (1)
#define HAVE_LVX_ASHIFT_V16HI (1)
#define HAVE_LVX_ASHIFT_V32QI (1)

#define HAVE_LVX_ASHIFTRT_DI (1)
#define HAVE_LVX_ASHIFTRT_V2SI (1)
#define HAVE_LVX_ASHIFTRT_V4HI (1)
#define HAVE_LVX_ASHIFTRT_V8QI (1)
#define HAVE_LVX_ASHIFTRT_V2DI (1)
#define HAVE_LVX_ASHIFTRT_V4SI (1)
#define HAVE_LVX_ASHIFTRT_V8HI (1)
#define HAVE_LVX_ASHIFTRT_V16QI (1)
#define HAVE_LVX_ASHIFTRT_V4DI (1)
#define HAVE_LVX_ASHIFTRT_V8SI (1)
#define HAVE_LVX_ASHIFTRT_V16HI (1)
#define HAVE_LVX_ASHIFTRT_V32QI (1)

#define HAVE_LVX_AVG_DI (0)
#define HAVE_LVX_AVG_V2SI (1)
#define HAVE_LVX_AVG_V4HI (1)
#define HAVE_LVX_AVG_V8QI (1)
#define HAVE_LVX_AVG_V2DI (0)
#define HAVE_LVX_AVG_V4SI (1)
#define HAVE_LVX_AVG_V8HI (1)
#define HAVE_LVX_AVG_V16QI (1)
#define HAVE_LVX_AVG_V4DI (0)
#define HAVE_LVX_AVG_V8SI (1)
#define HAVE_LVX_AVG_V16HI (1)
#define HAVE_LVX_AVG_V32QI (1)

#define HAVE_LVX_CEIL_AVG_DI (0)
#define HAVE_LVX_CEIL_AVG_V2SI (1)
#define HAVE_LVX_CEIL_AVG_V4HI (1)
#define HAVE_LVX_CEIL_AVG_V8QI (1)
#define HAVE_LVX_CEIL_AVG_V2DI (0)
#define HAVE_LVX_CEIL_AVG_V4SI (1)
#define HAVE_LVX_CEIL_AVG_V8HI (1)
#define HAVE_LVX_CEIL_AVG_V16QI (1)
#define HAVE_LVX_CEIL_AVG_V4DI (0)
#define HAVE_LVX_CEIL_AVG_V8SI (1)
#define HAVE_LVX_CEIL_AVG_V16HI (1)
#define HAVE_LVX_CEIL_AVG_V32QI (1)

#define HAVE_LVX_CEIL_UAVG_DI (0)
#define HAVE_LVX_CEIL_UAVG_V2SI (1)
#define HAVE_LVX_CEIL_UAVG_V4HI (1)
#define HAVE_LVX_CEIL_UAVG_V8QI (1)
#define HAVE_LVX_CEIL_UAVG_V2DI (0)
#define HAVE_LVX_CEIL_UAVG_V4SI (1)
#define HAVE_LVX_CEIL_UAVG_V8HI (1)
#define HAVE_LVX_CEIL_UAVG_V16QI (1)
#define HAVE_LVX_CEIL_UAVG_V4DI (0)
#define HAVE_LVX_CEIL_UAVG_V8SI (1)
#define HAVE_LVX_CEIL_UAVG_V16HI (1)
#define HAVE_LVX_CEIL_UAVG_V32QI (1)

#define HAVE_LVX_COND_MOV_OI (1)
#define HAVE_LVX_COND_MOV_V32QI (1)
#define HAVE_LVX_COND_MOV_V16HI (1)
#define HAVE_LVX_COND_MOV_V16HF (1)
#define HAVE_LVX_COND_MOV_V8SI (1)
#define HAVE_LVX_COND_MOV_V8SF (1)
#define HAVE_LVX_COND_MOV_V4DI (1)
#define HAVE_LVX_COND_MOV_V4DF (1)


#define HAVE_LVX_CPLX_FMA_V2SF (1)
#define HAVE_LVX_CPLX_FMA_V4SF (0)
#define HAVE_LVX_CPLX_FMS_V2SF (1)
#define HAVE_LVX_CPLX_FMS_V4SF (0)
#define HAVE_LVX_CPLX_CONJ_V16QI (1)
#define HAVE_LVX_CPLX_CONJ_V4HI (0)
#define HAVE_LVX_CPLX_CONJ_V4SI (0)
#define HAVE_LVX_CPLX_CONJ_V8HI (0)
#define HAVE_LVX_CPLX_CONJ_V8QI (1)
#define HAVE_LVX_CPLX_FMA_V2SF_V2SF_V2SF (1)
#define HAVE_LVX_CPLX_FMA_V4SF_V4SF_V4SF (1)
#define HAVE_LVX_CPLX_FMS_V2SF_V2SF_V2SF (1)
#define HAVE_LVX_CPLX_FMS_V4SF_V4SF_V4SF (0)
#define HAVE_LVX_CPLX_MINUS_V2HI (0)
#define HAVE_LVX_CPLX_MINUS_V2SI (0)
#define HAVE_LVX_CPLX_MINUS_CONJ_V4HI (0)
#define HAVE_LVX_CPLX_MULT_V2SF (1)
#define HAVE_LVX_CPLX_MULT_V4SF (0)
#define HAVE_LVX_CPLX_MULT_V2SI (0)
#define HAVE_LVX_CPLX_MULT_V4SI (0)
#define HAVE_LVX_CPLX_PLUS_V2DF (0)
#define HAVE_LVX_CPLX_PLUS_V2HI (0)
#define HAVE_LVX_CPLX_PLUS_V2SF (0)
#define HAVE_LVX_CPLX_PLUS_V2SI (0)
#define HAVE_LVX_CPLX_PLUS_V4SF (0)
#define HAVE_LVX_CPLX_PLUS_CONJ_V4HI (0)
#define HAVE_LVX_CPLX_PLUS_CONJ_V4SF (0)
#define HAVE_LVX_CPLX_PLUS_CONJ_V2SF (0)
#define HAVE_LVX_CPLX_PLUS_CONJ_V2DF (0)
#define HAVE_LVX_CPLX_MINUS_CONJ_V2SF (0)
#define HAVE_LVX_CPLX_MINUS_CONJ_V4SF (0)
#define HAVE_LVX_CPLX_MINUS_CONJ_V2DF (0)

#define HAVE_LVX_DIV_V16QI (1)
#define HAVE_LVX_DIV_V32QI (1)
#define HAVE_LVX_DIV_V4HI (1)
#define HAVE_LVX_DIV_V8QI (1)

#define HAVE_LVX_FCDIV_DF (1)
#define HAVE_LVX_FCDIV_SF (1)
#define HAVE_LVX_FCDIV_V2SF (1)

#define HAVE_LVX_FDMAS_SF_V2SF_V2SF (1)
#define HAVE_LVX_FDMAS_V2SF_V4SF_V4SF (1)
#define HAVE_LVX_FDMAS_V4SF_V8SF_V8SF (1)

#define HAVE_LVX_FDMDA_SF_V2SF_V2SF (1)
#define HAVE_LVX_FDMDA_V2SF_V4SF_V4SF (1)
#define HAVE_LVX_FDMDA_V4SF_V8SF_V8SF (1)

#define HAVE_LVX_FDMDS_SF_V2SF_V2SF (1)
#define HAVE_LVX_FDMDS_V2SF_V4SF_V4SF (1)
#define HAVE_LVX_FDMDS_V4SF_V8SF_V8SF (1)

#define HAVE_LVX_FDMSA_SF_V2SF_V2SF (1)
#define HAVE_LVX_FDMSA_V2SF_V4SF_V4SF (1)
#define HAVE_LVX_FDMSA_V4SF_V8SF_V8SF (1)

#define HAVE_LVX_FDMS_SF_V2SF_V2SF (1)
#define HAVE_LVX_FDMS_V2SF_V4SF_V4SF (1)
#define HAVE_LVX_FDMS_V4SF_V8SF_V8SF (1)

#define HAVE_LVX_FDOT_DF_V2SF_V2SF (0)
#define HAVE_LVX_FDOT_SF_V2SF_V2SF (0)
#define HAVE_LVX_FDOT_V2DF_V4SF_V4SF (0)
#define HAVE_LVX_FDOT_V4SF_V4SF_V4SF (0)

#define HAVE_LVX_FMA_DF_DF_DF (1) // ffmad
#define HAVE_LVX_FMA_DF_SF_SF (0) // ffmawd
#define HAVE_LVX_FMA_SF_HF_HF (0) // ffmahw
#define HAVE_LVX_FMA_SF_SF_SF (1) // ffmaw
#define HAVE_LVX_FMA_V2DF_V2DF_V2DF (0) // ffmadp
#define HAVE_LVX_FMA_V2DF_V2SF_V2SF (1) // ffmawp
#define HAVE_LVX_FMA_V2SI (LVX_1)
#define HAVE_LVX_FMA_V4HF_V4HF_V4HF (1) // ffmahq
#define HAVE_LVX_FMA_V4SF_V4HF_V4HF (0) // ffmahwq
#define HAVE_LVX_FMA_V4SF_V4SF_V4SF (0) // ffmawp
#define HAVE_LVX_FMA_V4SI (0)
#define HAVE_LVX_FMA_V8HF_V8HF_V8HF (0) // ffmaho

#define HAVE_LVX_FMS_DF_DF_DF (1) // ffmsd
#define HAVE_LVX_FMS_DF_SF_SF (0) // ffmswd
#define HAVE_LVX_FMS_SF_HF_HF (0) // ffmshw
#define HAVE_LVX_FMS_SF_SF_SF (1) // ffmsw
#define HAVE_LVX_FMS_V2DF_V2DF_V2DF (0) // ffmsdp
#define HAVE_LVX_FMS_V2DF_V2SF_V2SF (1) // ffmswp
#define HAVE_LVX_FMS_V2SI (LVX_1)
#define HAVE_LVX_FMS_V4HF_V4HF_V4HF (1) // ffmshq
#define HAVE_LVX_FMS_V4SF_V4HF_V4HF (0) // ffmshwq
#define HAVE_LVX_FMS_V4SF_V4SF_V4SF (0) // ffmswp
#define HAVE_LVX_FMS_V4SI (0)
#define HAVE_LVX_FMS_V8HF_V8HF_V8HF (0) // ffmsho

#define HAVE_LVX_FSDIV_DF (1)
#define HAVE_LVX_FSDIV_SF (1)
#define HAVE_LVX_FSDIV_V2SF (1)

#define HAVE_LVX_HAVE_SS_PLUS_V16HI (1)
#define HAVE_LVX_HAVE_SS_PLUS_V4DI (1)
#define HAVE_LVX_HAVE_SS_PLUS_V8SI (1)

#define HAVE_LVX_IOR_DI (1)
#define HAVE_LVX_IOR_SI (1)
#define HAVE_LVX_IOR_V16HI (1)
#define HAVE_LVX_IOR_V16QI (1)
#define HAVE_LVX_IOR_V2DI (1)
#define HAVE_LVX_IOR_V2SI (1)
#define HAVE_LVX_IOR_V32QI (1)
#define HAVE_LVX_IOR_V4DI (1)
#define HAVE_LVX_IOR_V4HI (1)
#define HAVE_LVX_IOR_V4SI (1)
#define HAVE_LVX_IOR_V8HI (1)
#define HAVE_LVX_IOR_V8QI (1)
#define HAVE_LVX_IOR_V8SI (1)
#define HAVE_LVX_IORN_DI (1)
#define HAVE_LVX_IORN_SI (1)

#define HAVE_LVX_LSHIFTRT_DI (1)
#define HAVE_LVX_LSHIFTRT_V2SI (1)
#define HAVE_LVX_LSHIFTRT_V4HI (1)
#define HAVE_LVX_LSHIFTRT_V8QI (1)
#define HAVE_LVX_LSHIFTRT_V2DI (1)
#define HAVE_LVX_LSHIFTRT_V4SI (1)
#define HAVE_LVX_LSHIFTRT_V8HI (1)
#define HAVE_LVX_LSHIFTRT_V16QI (1)
#define HAVE_LVX_LSHIFTRT_V4DI (1)
#define HAVE_LVX_LSHIFTRT_V8SI (1)
#define HAVE_LVX_LSHIFTRT_V16HI (1)
#define HAVE_LVX_LSHIFTRT_V32QI (1)

#define HAVE_LVX_MA_M2x2_SF_M2x2_SF_M2x2_SF (1)

#define HAVE_LVX_MIN_V8QI (1)
#define HAVE_LVX_MIN_V16QI (1)
#define HAVE_LVX_MIN_V32QI (1)
#define HAVE_LVX_MIN_V4HI (1)
#define HAVE_LVX_MIN_SI (1)
#define HAVE_LVX_MIN_V2SI (1)
#define HAVE_LVX_MIN_DI (1)
#define HAVE_LVX_MIN_HF (1)
#define HAVE_LVX_MIN_V4HF (1)
#define HAVE_LVX_MIN_V8HF (1)
#define HAVE_LVX_MIN_SF (1)
#define HAVE_LVX_MIN_V2SF (1)
#define HAVE_LVX_MIN_V4SF (1)
#define HAVE_LVX_MIN_DF (1)
#define HAVE_LVX_MIN_V2DF (1)

#define HAVE_LVX_UMIN_V8QI (1)
#define HAVE_LVX_UMIN_V16QI (1)
#define HAVE_LVX_UMIN_V32QI (1)
#define HAVE_LVX_UMIN_V4HI (0)
#define HAVE_LVX_UMIN_SI (0)
#define HAVE_LVX_UMIN_V2SI (0)
#define HAVE_LVX_UMIN_DI (0)

#define HAVE_LVX_MAX_V8QI (1)
#define HAVE_LVX_MAX_V16QI (1)
#define HAVE_LVX_MAX_V32QI (1)
#define HAVE_LVX_MAX_V4HI (1)
#define HAVE_LVX_MAX_SI (1)
#define HAVE_LVX_MAX_V2SI (1)
#define HAVE_LVX_MAX_DI (1)
#define HAVE_LVX_MAX_HF (1)
#define HAVE_LVX_MAX_V4HF (1)
#define HAVE_LVX_MAX_V8HF (1)
#define HAVE_LVX_MAX_SF (1)
#define HAVE_LVX_MAX_V2SF (1)
#define HAVE_LVX_MAX_V4SF (1)
#define HAVE_LVX_MAX_DF (1)
#define HAVE_LVX_MAX_V2DF (1)

#define HAVE_LVX_UMAX_V8QI (1)
#define HAVE_LVX_UMAX_V16QI (1)
#define HAVE_LVX_UMAX_V32QI (1)
#define HAVE_LVX_UMAX_V4HI (0)
#define HAVE_LVX_UMAX_SI (0)
#define HAVE_LVX_UMAX_V2SI (0)
#define HAVE_LVX_UMAX_DI (0)

#define HAVE_LVX_MINUS_V16QI (1)
#define HAVE_LVX_MINUS_V2DF (0)
#define HAVE_LVX_MINUS_V2SF (1)
#define HAVE_LVX_MINUS_V32QI (1)
#define HAVE_LVX_MINUS_V4HI (1)
#define HAVE_LVX_MINUS_V4SF (0)
#define HAVE_LVX_MINUS_V8HF (0)
#define HAVE_LVX_MINUS_V8QI (1)

#define HAVE_LVX_MOD_V16QI (1)
#define HAVE_LVX_MOD_V32QI (1)
#define HAVE_LVX_MOD_V4HI (1)
#define HAVE_LVX_MOD_V8QI (1)

#define HAVE_LVX_MOV_FROM_CORE_V1DI_TO_EXT_V1OI (1)
#define HAVE_LVX_MOV_FROM_CORE_V2DI_TO_EXT_V1OI (1)
#define HAVE_LVX_MOV_FROM_CORE_V4DI_TO_EXT_V1OI (1)

#define HAVE_LVX_MOV_FROM_EXT_V1OI_TO_CORE_V1DI (1)
#define HAVE_LVX_MOV_FROM_EXT_V1OI_TO_CORE_V2DI (1)
#define HAVE_LVX_MOV_FROM_EXT_V1OI_TO_CORE_V4DI (1)

#define HAVE_LVX_MS_M2x2_SF_M2x2_SF_M2x2_SF (1)

#define HAVE_LVX_MULT_DF_SF_SF (0)
#define HAVE_LVX_MULT_M2x2_SF_M2x2_SF_M2x2_SF (1)
#define HAVE_LVX_MULT_SF_HF_HF (0)
#define HAVE_LVX_MULT_V16QI (1)
#define HAVE_LVX_MULT_V2DF (0)
#define HAVE_LVX_MULT_V2DF_V2SF_V2SF (0)
#define HAVE_LVX_MULT_V2SF (1)
#define HAVE_LVX_MULT_V32QI (1)
#define HAVE_LVX_MULT_V4SF (0)
#define HAVE_LVX_MULT_V4SF_V4HF_V4HF (0)
#define HAVE_LVX_MULT_V8HF (0)
#define HAVE_LVX_MULT_V8QI (1)

#define HAVE_LVX_CMP_SF (1)
#define HAVE_LVX_CMP_DF (1)
#define HAVE_LVX_CMP_V2DF (1)
#define HAVE_LVX_CMP_V4SF (0)
#define HAVE_LVX_CMP_V8HF (0)
#define HAVE_LVX_CMP_V4DI (1) // FIXME: lvx-1
#define HAVE_LVX_CMP_V4DF (0)

#define HAVE_LVX_NEG_CMP_HF (0)
#define HAVE_LVX_NEG_CMP_DF (1)
#define HAVE_LVX_NEG_CMP_DI (1)
#define HAVE_LVX_NEG_CMP_SF (1)
#define HAVE_LVX_NEG_CMP_SI (1)
#define HAVE_LVX_NEG_CMP_V2SF (1)
#define HAVE_LVX_NEG_CMP_V4SF (1)
#define HAVE_LVX_NEG_CMP_V2SI (1)
#define HAVE_LVX_NEG_CMP_V4HF (1)
#define HAVE_LVX_NEG_CMP_V8HF (1)
#define HAVE_LVX_NEG_CMP_V4HI (1)
#define HAVE_LVX_NEG_CMP_V8QI (1)
/* No COMPND/FCOMPND: the negated compare was a 64-bit SIMD instruction, and
   that family is gone from LVX.  0 selects the compare-then-negate splits in
   control.md, which is how these modes are covered now.  */
#define HAVE_LVX_NEG_CMP_V2DI (0)
#define HAVE_LVX_NEG_CMP_V4DI (1)
#define HAVE_LVX_NEG_CMP_V2DF (0)

#define HAVE_LVX_NEG_CMP_V16HF (0)
#define HAVE_LVX_NEG_CMP_V4DF (0)
#define HAVE_LVX_NEG_CMP_V8SF (0)

#define HAVE_LVX_NEG_DI (1)
#define HAVE_LVX_NEG_QI (1)
#define HAVE_LVX_NEG_SI (1)
#define HAVE_LVX_NEG_V16QI (1)
#define HAVE_LVX_NEG_V2SI (1)
#define HAVE_LVX_NEG_V32QI (1)
#define HAVE_LVX_NEG_V4HI (1)
#define HAVE_LVX_NEG_V8QI (1)

#define HAVE_LVX_PLUS_V16QI (1)
#define HAVE_LVX_PLUS_V2DF (0)
#define HAVE_LVX_PLUS_V2SF (1)
#define HAVE_LVX_PLUS_V32QI (1)
#define HAVE_LVX_PLUS_V4SF (0)
#define HAVE_LVX_PLUS_V8HF (0)
#define HAVE_LVX_PLUS_V8QI (1)

#define HAVE_LVX_SBMM8_DI (1)
#define HAVE_LVX_SBMM8_DF (1)
#define HAVE_LVX_SBMM8_V8QI (1)
#define HAVE_LVX_SBMM8_V4HI (1)
#define HAVE_LVX_SBMM8_V4HF (1)
#define HAVE_LVX_SBMM8_V2SI (1)
#define HAVE_LVX_SBMM8_V2SF (1)
#define HAVE_LVX_SBMM8_V1DI (1)
#define HAVE_LVX_SBMM8_V2DI (1)
#define HAVE_LVX_SBMM8_TI (1)
#define HAVE_LVX_SBMM8_V16QI (1)
#define HAVE_LVX_SBMM8_V8HI (1)
#define HAVE_LVX_SBMM8_V8HF (1)
#define HAVE_LVX_SBMM8_V4SI (1)
#define HAVE_LVX_SBMM8_V4SF (1)
#define HAVE_LVX_SBMM8_V2DF (1)
#define HAVE_LVX_SBMM8_V4DF (1)
#define HAVE_LVX_SBMM8_V8SI (1)
#define HAVE_LVX_SBMM8_V8SF (1)
#define HAVE_LVX_SBMM8_V16HF (1)
#define HAVE_LVX_SBMM8_V16HI (1)
#define HAVE_LVX_SBMM8_V32QI (1)
#define HAVE_LVX_SBMM8_OI (1)
#define HAVE_LVX_SBMM8_V4DI (1)

#define HAVE_LVX_TSBMM8_DI (1)
#define HAVE_LVX_TSBMM8_DF (1)
#define HAVE_LVX_TSBMM8_V8QI (1)
#define HAVE_LVX_TSBMM8_V4HI (1)
#define HAVE_LVX_TSBMM8_V4HF (1)
#define HAVE_LVX_TSBMM8_V2SI (1)
#define HAVE_LVX_TSBMM8_V2SF (1)
#define HAVE_LVX_TSBMM8_V1DI (1)
#define HAVE_LVX_TSBMM8_V2DI (1)
#define HAVE_LVX_TSBMM8_TI (1)
#define HAVE_LVX_TSBMM8_V16QI (1)
#define HAVE_LVX_TSBMM8_V8HI (1)
#define HAVE_LVX_TSBMM8_V8HF (1)
#define HAVE_LVX_TSBMM8_V4SI (1)
#define HAVE_LVX_TSBMM8_V4SF (1)
#define HAVE_LVX_TSBMM8_V2DF (1)
#define HAVE_LVX_TSBMM8_V4DF (1)
#define HAVE_LVX_TSBMM8_V8SI (1)
#define HAVE_LVX_TSBMM8_V8SF (1)
#define HAVE_LVX_TSBMM8_V16HF (1)
#define HAVE_LVX_TSBMM8_V16HI (1)
#define HAVE_LVX_TSBMM8_V32QI (1)
#define HAVE_LVX_TSBMM8_OI (1)
#define HAVE_LVX_TSBMM8_V4DI (1)

#define HAVE_LVX_SELECT_V16HF (1)
#define HAVE_LVX_SELECT_V16HI (1)
#define HAVE_LVX_SELECT_V16QI (1)
#define HAVE_LVX_SELECT_V32QI (1)
#define HAVE_LVX_SELECT_V4DF (1)
#define HAVE_LVX_SELECT_V4DI (1)
#define HAVE_LVX_SELECT_V64QI (1)
#define HAVE_LVX_SELECT_V8QI (1)
#define HAVE_LVX_SELECT_V8SF (1)
#define HAVE_LVX_SELECT_V8SI (1)


#define HAVE_LVX_MUL02_ADD_SI (1)
#define HAVE_LVX_MUL02_ADD_DI (1)
#define HAVE_LVX_MUL02_ADD_V2SI (1)
#define HAVE_LVX_MUL02_ADD_V4HI (1)
#define HAVE_LVX_MUL02_ADD_V8QI (1)
#define HAVE_LVX_MUL02_ADD_V2DI (1)
#define HAVE_LVX_MUL02_ADD_V4SI (1)
#define HAVE_LVX_MUL02_ADD_V8HI (1)
#define HAVE_LVX_MUL02_ADD_V16QI (1)
#define HAVE_LVX_MUL02_ADD_V4DI (1)
#define HAVE_LVX_MUL02_ADD_V8SI (1)
#define HAVE_LVX_MUL02_ADD_V16HI (1)
#define HAVE_LVX_MUL02_ADD_V32QI (1)

#define HAVE_LVX_MUL02_SUB_SI (0)
#define HAVE_LVX_MUL02_SUB_DI (0)
#define HAVE_LVX_MUL02_SUB_V2SI (0)
#define HAVE_LVX_MUL02_SUB_V4HI (0)
#define HAVE_LVX_MUL02_SUB_V8QI (0)
#define HAVE_LVX_MUL02_SUB_V2DI (0)
#define HAVE_LVX_MUL02_SUB_V4SI (0)
#define HAVE_LVX_MUL02_SUB_V8HI (0)
#define HAVE_LVX_MUL02_SUB_V16QI (0)
#define HAVE_LVX_MUL02_SUB_V4DI (0)
#define HAVE_LVX_MUL02_SUB_V8SI (0)
#define HAVE_LVX_MUL02_SUB_V16HI (0)
#define HAVE_LVX_MUL02_SUB_V32QI (0)

#define HAVE_LVX_MUL04_ADD_SI (1)
#define HAVE_LVX_MUL04_ADD_DI (1)
#define HAVE_LVX_MUL04_ADD_V2SI (1)
#define HAVE_LVX_MUL04_ADD_V4HI (1)
#define HAVE_LVX_MUL04_ADD_V8QI (1)
#define HAVE_LVX_MUL04_ADD_V2DI (1)
#define HAVE_LVX_MUL04_ADD_V4SI (1)
#define HAVE_LVX_MUL04_ADD_V8HI (1)
#define HAVE_LVX_MUL04_ADD_V16QI (1)
#define HAVE_LVX_MUL04_ADD_V4DI (1)
#define HAVE_LVX_MUL04_ADD_V8SI (1)
#define HAVE_LVX_MUL04_ADD_V16HI (1)
#define HAVE_LVX_MUL04_ADD_V32QI (1)

#define HAVE_LVX_MUL04_SUB_SI (0)
#define HAVE_LVX_MUL04_SUB_DI (0)
#define HAVE_LVX_MUL04_SUB_V2SI (0)
#define HAVE_LVX_MUL04_SUB_V4HI (0)
#define HAVE_LVX_MUL04_SUB_V8QI (0)
#define HAVE_LVX_MUL04_SUB_V2DI (0)
#define HAVE_LVX_MUL04_SUB_V4SI (0)
#define HAVE_LVX_MUL04_SUB_V8HI (0)
#define HAVE_LVX_MUL04_SUB_V16QI (0)
#define HAVE_LVX_MUL04_SUB_V4DI (0)
#define HAVE_LVX_MUL04_SUB_V8SI (0)
#define HAVE_LVX_MUL04_SUB_V16HI (0)
#define HAVE_LVX_MUL04_SUB_V32QI (0)

#define HAVE_LVX_MUL08_ADD_SI (1)
#define HAVE_LVX_MUL08_ADD_DI (1)
#define HAVE_LVX_MUL08_ADD_V2SI (1)
#define HAVE_LVX_MUL08_ADD_V4HI (1)
#define HAVE_LVX_MUL08_ADD_V8QI (1)
#define HAVE_LVX_MUL08_ADD_V2DI (1)
#define HAVE_LVX_MUL08_ADD_V4SI (1)
#define HAVE_LVX_MUL08_ADD_V8HI (1)
#define HAVE_LVX_MUL08_ADD_V16QI (1)
#define HAVE_LVX_MUL08_ADD_V4DI (1)
#define HAVE_LVX_MUL08_ADD_V8SI (1)
#define HAVE_LVX_MUL08_ADD_V16HI (1)
#define HAVE_LVX_MUL08_ADD_V32QI (1)

#define HAVE_LVX_MUL08_SUB_SI (0)
#define HAVE_LVX_MUL08_SUB_DI (0)
#define HAVE_LVX_MUL08_SUB_V2SI (0)
#define HAVE_LVX_MUL08_SUB_V4HI (0)
#define HAVE_LVX_MUL08_SUB_V8QI (0)
#define HAVE_LVX_MUL08_SUB_V2DI (0)
#define HAVE_LVX_MUL08_SUB_V4SI (0)
#define HAVE_LVX_MUL08_SUB_V8HI (0)
#define HAVE_LVX_MUL08_SUB_V16QI (0)
#define HAVE_LVX_MUL08_SUB_V4DI (0)
#define HAVE_LVX_MUL08_SUB_V8SI (0)
#define HAVE_LVX_MUL08_SUB_V16HI (0)
#define HAVE_LVX_MUL08_SUB_V32QI (0)

#define HAVE_LVX_MUL16_ADD_SI (1)
#define HAVE_LVX_MUL16_ADD_DI (1)
#define HAVE_LVX_MUL16_ADD_V2SI (1)
#define HAVE_LVX_MUL16_ADD_V4HI (1)
#define HAVE_LVX_MUL16_ADD_V8QI (1)
#define HAVE_LVX_MUL16_ADD_V2DI (1)
#define HAVE_LVX_MUL16_ADD_V4SI (1)
#define HAVE_LVX_MUL16_ADD_V8HI (1)
#define HAVE_LVX_MUL16_ADD_V16QI (1)
#define HAVE_LVX_MUL16_ADD_V4DI (1)
#define HAVE_LVX_MUL16_ADD_V8SI (1)
#define HAVE_LVX_MUL16_ADD_V16HI (1)
#define HAVE_LVX_MUL16_ADD_V32QI (1)

#define HAVE_LVX_MUL16_SUB_SI (0)
#define HAVE_LVX_MUL16_SUB_DI (0)
#define HAVE_LVX_MUL16_SUB_V2SI (0)
#define HAVE_LVX_MUL16_SUB_V4HI (0)
#define HAVE_LVX_MUL16_SUB_V8QI (0)
#define HAVE_LVX_MUL16_SUB_V2DI (0)
#define HAVE_LVX_MUL16_SUB_V4SI (0)
#define HAVE_LVX_MUL16_SUB_V8HI (0)
#define HAVE_LVX_MUL16_SUB_V16QI (0)
#define HAVE_LVX_MUL16_SUB_V4DI (0)
#define HAVE_LVX_MUL16_SUB_V8SI (0)
#define HAVE_LVX_MUL16_SUB_V16HI (0)
#define HAVE_LVX_MUL16_SUB_V32QI (0)

#define HAVE_LVX_MUL32_ADD_SI (1)
#define HAVE_LVX_MUL32_ADD_DI (1)
#define HAVE_LVX_MUL32_SUB_SI (0)
#define HAVE_LVX_MUL32_SUB_DI (0)

#define HAVE_LVX_MUL64_ADD_SI (1)
#define HAVE_LVX_MUL64_ADD_DI (1)
#define HAVE_LVX_MUL64_SUB_SI (0)
#define HAVE_LVX_MUL64_SUB_DI (0)

#define HAVE_LVX_SMAX_V16QI (1)
#define HAVE_LVX_SMAX_V32QI (1)
#define HAVE_LVX_SMAX_V8QI (1)

#define HAVE_LVX_SMIN_V16QI (1)
#define HAVE_LVX_SMIN_V32QI (1)
#define HAVE_LVX_SMIN_V8QI (1)

#define HAVE_LVX_SS_ABD_DI (1)
#define HAVE_LVX_SS_ABD_SI (1)
#define HAVE_LVX_SS_ABD_V16HI (1)
#define HAVE_LVX_SS_ABD_V16QI (1)
#define HAVE_LVX_SS_ABD_V2DI (1)
#define HAVE_LVX_SS_ABD_V2SI (1)
#define HAVE_LVX_SS_ABD_V32QI (1)
#define HAVE_LVX_SS_ABD_V4DI (1)
#define HAVE_LVX_SS_ABD_V4HI (1)
#define HAVE_LVX_SS_ABD_V4SI (1)
#define HAVE_LVX_SS_ABD_V8HI (1)
#define HAVE_LVX_SS_ABD_V8QI (1)
#define HAVE_LVX_SS_ABD_V8SI (1)

#define HAVE_LVX_SS_ABS_DI (1)
#define HAVE_LVX_SS_ABS_SI (1)
#define HAVE_LVX_SS_ABS_V16HI (1)
#define HAVE_LVX_SS_ABS_V16QI (1)
#define HAVE_LVX_SS_ABS_V2DI (1)
#define HAVE_LVX_SS_ABS_V2SI (1)
#define HAVE_LVX_SS_ABS_V32QI (1)
#define HAVE_LVX_SS_ABS_V4DI (1)
#define HAVE_LVX_SS_ABS_V4HI (1)
#define HAVE_LVX_SS_ABS_V4SI (1)
#define HAVE_LVX_SS_ABS_V8HI (1)
#define HAVE_LVX_SS_ABS_V8QI (1)
#define HAVE_LVX_SS_ABS_V8SI (1)

#define HAVE_LVX_SS_ASHIFT_V16QI (1)
#define HAVE_LVX_SS_ASHIFT_V32QI (1)
#define HAVE_LVX_SS_ASHIFT_V8QI (1)

#define HAVE_LVX_SSHR_V16QI (1)
#define HAVE_LVX_SSHR_V32QI (1)
#define HAVE_LVX_SSHR_V8QI (1)

#define HAVE_LVX_SS_MINUS_DI (1)
#define HAVE_LVX_SS_MINUS_V2SI (1)
#define HAVE_LVX_SS_MINUS_V4HI (1)
#define HAVE_LVX_SS_MINUS_V8QI (1)
#define HAVE_LVX_SS_MINUS_V2DI (1)
#define HAVE_LVX_SS_MINUS_V4SI (1)
#define HAVE_LVX_SS_MINUS_V8HI (1)
#define HAVE_LVX_SS_MINUS_V16QI (1)
#define HAVE_LVX_SS_MINUS_V4DI (1)
#define HAVE_LVX_SS_MINUS_V8SI (1)
#define HAVE_LVX_SS_MINUS_V16HI (1)
#define HAVE_LVX_SS_MINUS_V32QI (1)

#define HAVE_LVX_SS_NEG_DI (1)
#define HAVE_LVX_SS_NEG_V2SI (1)
#define HAVE_LVX_SS_NEG_V4HI (1)
#define HAVE_LVX_SS_NEG_V8QI (1)
#define HAVE_LVX_SS_NEG_V2DI (1)
#define HAVE_LVX_SS_NEG_V4SI (1)
#define HAVE_LVX_SS_NEG_V8HI (1)
#define HAVE_LVX_SS_NEG_V16QI (1)
#define HAVE_LVX_SS_NEG_V4DI (1)
#define HAVE_LVX_SS_NEG_V8SI (1)
#define HAVE_LVX_SS_NEG_V16HI (1)
#define HAVE_LVX_SS_NEG_V32QI (1)

#define HAVE_LVX_SS_PLUS_DI (1)
#define HAVE_LVX_SS_PLUS_V2SI (1)
#define HAVE_LVX_SS_PLUS_V4HI (1)
#define HAVE_LVX_SS_PLUS_V8QI (1)
#define HAVE_LVX_SS_PLUS_V2DI (1)
#define HAVE_LVX_SS_PLUS_V4SI (1)
#define HAVE_LVX_SS_PLUS_V8HI (1)
#define HAVE_LVX_SS_PLUS_V16QI (1)
#define HAVE_LVX_SS_PLUS_V4DI (1)
#define HAVE_LVX_SS_PLUS_V8SI (1)
#define HAVE_LVX_SS_PLUS_V16HI (1)
#define HAVE_LVX_SS_PLUS_V32QI (1)

#define HAVE_LVX_STSU_DI (1)
#define HAVE_LVX_STSU_V2DI (1)
#define HAVE_LVX_STSU_V2SI (1)
#define HAVE_LVX_STSU_V4HI (1)
#define HAVE_LVX_STSU_V4DI (1)

#define HAVE_LVX_EXT_ANDN_V1OI (1)
#define HAVE_LVX_EXT_AND_V1OI (1)

#define HAVE_LVX_EXT_BUFFER_MOV_CORE_V4DI_V16OI (1)
#define HAVE_LVX_EXT_BUFFER_MOV_CORE_V4DI_V2OI (1)
#define HAVE_LVX_EXT_BUFFER_MOV_CORE_V4DI_V32OI (1)
#define HAVE_LVX_EXT_BUFFER_MOV_CORE_V4DI_V4OI (1)
#define HAVE_LVX_EXT_BUFFER_MOV_CORE_V4DI_V8OI (1)
#define HAVE_LVX_EXT_BUFFER_MOV_EXT_V1OI_V16OI (1)
#define HAVE_LVX_EXT_BUFFER_MOV_EXT_V1OI_V2OI (1)
#define HAVE_LVX_EXT_BUFFER_MOV_EXT_V1OI_V32OI (1)
#define HAVE_LVX_EXT_BUFFER_MOV_EXT_V1OI_V4OI (1)
#define HAVE_LVX_EXT_BUFFER_MOV_EXT_V1OI_V8OI (1)
#define HAVE_LVX_EXT_BUFFER_PRELOAD_V16OI (1)
#define HAVE_LVX_EXT_BUFFER_PRELOAD_V2OI (1)
#define HAVE_LVX_EXT_BUFFER_PRELOAD_V32OI (1)
#define HAVE_LVX_EXT_BUFFER_PRELOAD_V4OI (1)
#define HAVE_LVX_EXT_BUFFER_PRELOAD_V8OI (1)

#define HAVE_LVX_EXT_CACHED_LOAD (1)

#define HAVE_LVX_EXT_CLAMP_V8SI_V8SI_V8SI (1)
#define HAVE_LVX_EXT_CONVERT_M4x4_HF_M4x4_SF (1)
#define HAVE_LVX_EXT_COPY_V1OI (1)
#define HAVE_LVX_EXT_COPY_V2OI (1)
#define HAVE_LVX_EXT_COPY_V4OI (1)
#define HAVE_LVX_EXT_EOR_V1OI (1)
#define HAVE_LVX_EXT_FMA_M4x4_DI_M4x8_HI_TM4x8_HI (1)
#define HAVE_LVX_EXT_HPA_LO_M4x4_SF_M4x4_QF_M4x4_QF (1)
#define HAVE_LVX_EXT_IORN_V1OI (1)
#define HAVE_LVX_EXT_IOR_V1OI (1)
#define HAVE_LVX_EXT_MATRIX424_FMA_V2OI (LVX_1)
#define HAVE_LVX_EXT_MATRIX444_FMA_V2OI (LVX_1)

#define HAVE_LVX_EXT_MATRIX_FMA_M4x4_DI_M4x16_QI_TM16x4_QI (1)
#define HAVE_LVX_EXT_MATRIX_FMA_M4x4_DI_M4x16_QI_TM16x4_UQI (1)
#define HAVE_LVX_EXT_MATRIX_FMA_M4x4_DI_M4x16_UQI_TM16x4_QI (1)
#define HAVE_LVX_EXT_MATRIX_FMA_M4x4_DI_M4x16_UQI_TM16x4_UQI (1)
#define HAVE_LVX_EXT_MATRIX_FMA_M4x4_DI_M4x4_DI_M4x8_QI_TM8x4_QI (0)
#define HAVE_LVX_EXT_MATRIX_FMA_M4x4_DI_M4x4_DI_M4x8_QI_TM8x4_UQI (0)
#define HAVE_LVX_EXT_MATRIX_FMA_M4x4_DI_M4x4_DI_M4x8_UQI_TM8x4_QI (0)
#define HAVE_LVX_EXT_MATRIX_FMA_M4x4_DI_M4x4_DI_M4x8_UQI_TM8x4_UQI (0)
#define HAVE_LVX_EXT_MATRIX_FMA_M4x4_DI_M4x8_QI_TM8x4_QI (1)
#define HAVE_LVX_EXT_MATRIX_FMA_M4x4_DI_M4x8_QI_TM8x4_UQI (1)
#define HAVE_LVX_EXT_MATRIX_FMA_M4x4_DI_M4x8_UQI_TM8x4_QI (1)
#define HAVE_LVX_EXT_MATRIX_FMA_M4x4_DI_M4x8_UQI_TM8x4_UQI (1)

#define HAVE_LVX_EXT_MATRIX_SIGN_EXTEND_M4x8_DI_M4x8_QI (1)
#define HAVE_LVX_EXT_MATRIX_TRANSPOSE_M4x4_DI_M4x4_DI (1)
#define HAVE_LVX_EXT_MATRIX_TRUNC_M4x8_QI_M4x8_DI (1)
#define HAVE_LVX_EXT_MATRIX_ZERO_EXTEND_M4x8_DI_M4x8_QI (1)
#define HAVE_LVX_EXT_NAND_V1OI (1)
#define HAVE_LVX_EXT_NEOR_V1OI (1)
#define HAVE_LVX_EXT_NIOR_V1OI (1)
#define HAVE_LVX_EXT_RECV_V1OI (1)
#define HAVE_LVX_EXT_SATURATED_FMA_V8SI_V8SI_V8SF (1)
#define HAVE_LVX_EXT_SATURATED_FMS_V8SI_V8SI_V8SF (1)
#define HAVE_LVX_EXT_SBMM8_V1OI (1)
#define HAVE_LVX_EXT_SBMMT8_V1OI (1)
#define HAVE_LVX_EXT_SCALE_V1OI (1)
#define HAVE_LVX_EXT_SEND_RECV_V1OI (1)
#define HAVE_LVX_EXT_SEND_V1OI (1)
#define HAVE_LVX_EXT_SPLAT_V16OI (1)
#define HAVE_LVX_EXT_SPLAT_V2OI (1)
#define HAVE_LVX_EXT_SPLAT_V32OI (1)
#define HAVE_LVX_EXT_SPLAT_V4OI (1)
#define HAVE_LVX_EXT_SPLAT_V8OI (1)

#define HAVE_LVX_EXT_MIN_X256 (1)
#define HAVE_LVX_EXT_MAX_X256 (1)

#define HAVE_LVX_UABD_DI (1)
#define HAVE_LVX_UABD_SI (1)
#define HAVE_LVX_UABD_V16QI (1)
#define HAVE_LVX_UABD_V2DI (1)
#define HAVE_LVX_UABD_V2SI (1)
#define HAVE_LVX_UABD_V4HI (1)
#define HAVE_LVX_UABD_V4SI (1)
#define HAVE_LVX_UABD_V8HI (1)
#define HAVE_LVX_UABD_V8QI (1)

#define HAVE_LVX_UAVG_DI (0)
#define HAVE_LVX_UAVG_V2SI (1)
#define HAVE_LVX_UAVG_V4HI (1)
#define HAVE_LVX_UAVG_V8QI (1)
#define HAVE_LVX_UAVG_V2DI (0)
#define HAVE_LVX_UAVG_V4SI (1)
#define HAVE_LVX_UAVG_V8HI (1)
#define HAVE_LVX_UAVG_V16QI (1)
#define HAVE_LVX_UAVG_V4DI (0)
#define HAVE_LVX_UAVG_V8SI (1)
#define HAVE_LVX_UAVG_V16HI (1)
#define HAVE_LVX_UAVG_V32QI (1)

#define HAVE_LVX_UDIV_V16QI (1)
#define HAVE_LVX_UDIV_V32QI (1)
#define HAVE_LVX_UDIV_V4HI (1)
#define HAVE_LVX_UDIV_V8QI (1)
#define HAVE_LVX_UMOD_V16QI (1)
#define HAVE_LVX_UMOD_V32QI (1)
#define HAVE_LVX_UMOD_V4HI (1)
#define HAVE_LVX_UMOD_V8QI (1)
#define HAVE_LVX_US_ABD_V16HI (1)
#define HAVE_LVX_US_ABD_V32QI (1)
#define HAVE_LVX_US_ABD_V4DI (1)
#define HAVE_LVX_US_ABD_V8SI (1)
#define HAVE_LVX_US_ASHIFT_DI (1)
#define HAVE_LVX_US_ASHIFT_SI (1)
#define HAVE_LVX_US_ASHIFT_V16HI (1)
#define HAVE_LVX_US_ASHIFT_V16QI (1)
#define HAVE_LVX_US_ASHIFT_V2DI (1)
#define HAVE_LVX_US_ASHIFT_V2SI (1)
#define HAVE_LVX_US_ASHIFT_V32QI (1)
#define HAVE_LVX_US_ASHIFT_V4DI (1)
#define HAVE_LVX_US_ASHIFT_V4HI (1)
#define HAVE_LVX_US_ASHIFT_V4SI (1)
#define HAVE_LVX_US_ASHIFT_V8HI (1)
#define HAVE_LVX_US_ASHIFT_V8QI (1)
#define HAVE_LVX_US_ASHIFT_V8SI (1)
#define HAVE_LVX_US_MINUS_DI (1)
#define HAVE_LVX_US_MINUS_SI (1)
#define HAVE_LVX_US_MINUS_V16HI (1)
#define HAVE_LVX_US_MINUS_V16QI (1)
#define HAVE_LVX_US_MINUS_V2DI (1)
#define HAVE_LVX_US_MINUS_V2SI (1)
#define HAVE_LVX_US_MINUS_V32QI (1)
#define HAVE_LVX_US_MINUS_V4DI (1)
#define HAVE_LVX_US_MINUS_V4HI (1)
#define HAVE_LVX_US_MINUS_V4SI (1)
#define HAVE_LVX_US_MINUS_V8HI (1)
#define HAVE_LVX_US_MINUS_V8QI (1)
#define HAVE_LVX_US_MINUS_V8SI (1)
#define HAVE_LVX_US_PLUS_DI (1)
#define HAVE_LVX_US_PLUS_SI (1)
#define HAVE_LVX_US_PLUS_V16HI (1)
#define HAVE_LVX_US_PLUS_V16QI (1)
#define HAVE_LVX_US_PLUS_V2DI (1)
#define HAVE_LVX_US_PLUS_V2SI (1)
#define HAVE_LVX_US_PLUS_V32QI (1)
#define HAVE_LVX_US_PLUS_V4DI (1)
#define HAVE_LVX_US_PLUS_V4HI (1)
#define HAVE_LVX_US_PLUS_V4SI (1)
#define HAVE_LVX_US_PLUS_V8HI (1)
#define HAVE_LVX_US_PLUS_V8QI (1)
#define HAVE_LVX_US_PLUS_V8SI (1)

// Check those names
#define HAVE_LVX_FDMA_SF_V2SF_V2SF (0)
#define HAVE_LVX_FDMA_V2SF_V4SF_V4SF (0)
#define HAVE_LVX_FDMA_V4SF_V8SF_V8SF (0)

#define HAVE_LVX_ZERO_EXTEND_V8HI_V8QI \
  (HAVE_LVX_ZERO_EXTEND_HI_V4HI_V8QI && \
   HAVE_LVX_ZERO_EXTEND_LO_V4HI_V8QI)

#define HAVE_LVX_ZERO_EXTEND_HI_V4HI_V8QI (0)
#define HAVE_LVX_ZERO_EXTEND_LO_V4HI_V8QI (0)

#define HAVE_LVX_ZERO_EXTEND_V4SI_V4HI \
  (HAVE_LVX_ZERO_EXTEND_HI_V2SI_V4HI && \
   HAVE_LVX_ZERO_EXTEND_LO_V2SI_V4HI)

#define HAVE_LVX_ZERO_EXTEND_HI_V2SI_V4HI (0)
#define HAVE_LVX_ZERO_EXTEND_LO_V2SI_V4HI (0)

/* Hadamard Product Accumulate */
#define HAVE_LVX_EXT_MATRIX_HPA_M4x4_DI_M4x8_QI_M4x8_QI \
    (HAVE_LVX_EXT_MATRIX_LO_HPA_M4x4_DI_M4x8_QI_M4x8_QI  \
  && HAVE_LVX_EXT_MATRIX_HI_HPA_M4x4_DI_M4x8_QI_M4x8_QI)

#define HAVE_LVX_EXT_MATRIX_LO_HPA_M4x4_DI_M4x8_QI_M4x8_QI (1)
#define HAVE_LVX_EXT_MATRIX_HI_HPA_M4x4_DI_M4x8_QI_M4x8_QI (1)

#define HAVE_LVX_EXT_MATRIX_HPA_M4x4_DI_M4x8_QI_M4x8_UQI \
    (HAVE_LVX_EXT_MATRIX_LO_HPA_M4x4_DI_M4x8_QI_M4x8_UQI  \
  && HAVE_LVX_EXT_MATRIX_HI_HPA_M4x4_DI_M4x8_QI_M4x8_UQI)

#define HAVE_LVX_EXT_MATRIX_LO_HPA_M4x4_DI_M4x8_QI_M4x8_UQI (1)
#define HAVE_LVX_EXT_MATRIX_HI_HPA_M4x4_DI_M4x8_QI_M4x8_UQI (1)

#define HAVE_LVX_EXT_MATRIX_HPA_M4x4_DI_M4x8_UQI_M4x8_UQI \
    (HAVE_LVX_EXT_MATRIX_LO_HPA_M4x4_DI_M4x8_UQI_M4x8_UQI  \
  && HAVE_LVX_EXT_MATRIX_HI_HPA_M4x4_DI_M4x8_UQI_M4x8_UQI)

#define HAVE_LVX_EXT_MATRIX_LO_HPA_M4x4_DI_M4x8_UQI_M4x8_UQI (1)
#define HAVE_LVX_EXT_MATRIX_HI_HPA_M4x4_DI_M4x8_UQI_M4x8_UQI (1)


#define HAVE_LVX_EXT_MATRIX_M2x2_DI_M2x2_DI_M2x4_HI_TM2x4_HI \
    (HAVE_LVX_EXT_MATRIX_LO_M2x2_DI_M2x2_DI_M2x4_HI_TM2x4_HI  \
  && HAVE_LVX_EXT_MATRIX_HI_M2x2_DI_M2x2_DI_M2x4_HI_TM2x4_HI)

#define HAVE_LVX_EXT_MATRIX_LO_M2x2_DI_M2x2_DI_M2x4_HI_TM2x4_HI \
    (HAVE_LVX_EXT_MATRIX_LO_LO_M2x2_DI_M2x2_DI_M2x4_HI_TM2x4_HI  \
  && HAVE_LVX_EXT_MATRIX_LO_HI_M2x2_DI_M2x2_DI_M2x4_HI_TM2x4_HI)

#define HAVE_LVX_EXT_MATRIX_HI_M2x2_DI_M2x2_DI_M2x4_HI_TM2x4_HI \
    (HAVE_LVX_EXT_MATRIX_HI_LO_M2x2_DI_M2x2_DI_M2x4_HI_TM2x4_HI  \
  && HAVE_LVX_EXT_MATRIX_HI_HI_M2x2_DI_M2x2_DI_M2x4_HI_TM2x4_HI)

#define HAVE_LVX_EXT_MATRIX_LO_LO_M2x2_DI_M2x2_DI_M2x4_HI_TM2x4_HI (0)
#define HAVE_LVX_EXT_MATRIX_LO_HI_M2x2_DI_M2x2_DI_M2x4_HI_TM2x4_HI (0)

#define HAVE_LVX_EXT_MATRIX_HI_LO_M2x2_DI_M2x2_DI_M2x4_HI_TM2x4_HI (0)
#define HAVE_LVX_EXT_MATRIX_HI_HI_M2x2_DI_M2x2_DI_M2x4_HI_TM2x4_HI (0)

/* On the kv3-1 (not applicable to LVX), the instruction fmin/fmax and its derivatives are not compliant
   with the IEEE-754-2008 definition and should be avoided unless the code does
   not care about signaling NaNs.

   OpenCL:
    - fmax: Returns y if x < y, otherwise it returns x. If one
            argument is a NaN, fmax() returns the other
            argument. If both arguments are NaNs, fmax()
            returns a NaN.

    - fmin: Returns y if y < x, otherwise it returns x. If one
            argument is a NaN, fmin() returns the other argument.
            If both arguments are NaNs, fmin() returns a NaN.

The implementation guarantees:
  fmin(sNaN1, sNaN2) = sNaN1
  fmin(qNaN1, qNaN2) = qNaN1
  fmin(sNaN, qNaN) = fmin(qNaN, sNaN) = sNaN
  fmin(sNaN, x) = fmin(x, sNaN) = sNaN
  fmin(qNaN, x) = fmin(x, qNaN) = x
  fmin(+0, -0) = fmin(-0, +0) = -0
  if (x, y) != (0, 0), then fmin(x, y) = fmin(y, x) = (x < y) ? x : y
which means that unless compliance with signaling NaNs is required we can select
the instruction.  */
#define HAVE_LVX_BUG_FMIN (0)
#define HAVE_LVX_BUG_FMAX (0)

#endif
